### PR TITLE
Fix and improve docs/metadata on easing typings

### PR DESCRIPTION
**Pull request by cfuendev**
The documentation for the ea/ease property had an incorrect spelling of skew-y in its description.

<p align="center">

</p>

After some discussion with @familyfriendlymikey over the Discord server, we came up with a solution. This PR not only corrects the spelling error, but also improves the overall readability of both the code and the docs by updating to the metadata/comments/docs for the two-letter easing shorthands (ea, eb, ec, et, and eo), making it easier for developers to understand and utilize these properties.

<p align="center">

</p>

Hope this clears developers' doubts more effectively and brings more Imba apps with cool transitions to life. 🎉

### CODE REVIEW

**Comment by familyfriendlymikey** [comment]
Great work, thank you! Though we need to run the generate script. I'd be happy to do that but I get the feeling that you'd want to so I won't :)

**Comment by familyfriendlymikey** [comment]
Great work, thank you! We need to run the generate script. I'd be happy to do that but I get the feeling that you'd want to so I won't :)

**Comment by familyfriendlymikey** [comment]
Great work, thank you! Though we need to run the generate script. I'd be happy to do that but I get the feeling that you'd want to so I won't :)

**Comment by cfuendev** [comment]
> Great work, thank you! Though we need to run the generate script. I'd be happy to do that but I get the feeling that you'd want to so I won't :)

I ran it like this, but I don't see any changes. 🤔
image

**Comment by familyfriendlymikey** [comment]
Hmm, no changes on my end either. Let's merge for now and I'll look into it later.

**Review by familyfriendlymikey — APPROVED** [review]

**Comment by familyfriendlymikey** [comment]
Thanks again :)

**Pull request merged**
