### PR TITLE
Single file components

### PR DESCRIPTION
**Pull request by somebee**
## Description

Added the ability to include css in imba files. Wanted to keep syntax backwards compatible, so for now we use multiline comments to define these styles:

```imba

### css scoped
p {
  color: red;
}
###

tag App
  def render
    <self> <p> "This is red"

```

The compiler parses these blocks and exposes them in result.styles on the compiler output. The default imba/loader handles these much like vue/loader does for sfc. You can also use the imba compiler with '--inline-css' option to compile the style directly into the files.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by scanf** [comment]
LGTM

**Comment by iamtirado** [comment]
is sass or any other preprocessor supported?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by scanf** [comment]
It already works but you need to install the loaders for the Imba Webpack loader to handle it. Not sure how it works with parcel, maybe some adjustment is required?

If you are using Webpack the steps are roughly
```
yarn add -D style-loader css-loader sass-loader node-sass
```
Add the test rule
```
[...]
      {
              test: /\.sass$/,
              use: ['style-loader','css-loader','sass-loader']
            }
[...]
```

Then you can start writing
```
### sass
[...]
###

### sass scoped
[...]
###
```

**Comment by iamtirado** [comment]
I will try this. thanks.

**Comment by iamtirado** [comment]
I can get it to work on simple imbac project, but not on a webpack project with src and dist folders. Too noob.

**Pull request merged**
