### PR TITLE
add "browser" and "chrome" words as global special variables

### PR DESCRIPTION
**Pull request by Friz-zy**
## Add "browser" and "chrome" words as global special variables

Words "browser" and "chrome" used in APIs for web extensions:
* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API
* https://developer.chrome.com/apps/api_index

Problem: currently imba convert `browser` word into `self.browser()`

## How Has This Been Tested?

I made manual changes of my global imba installation and used it for generation new not minified code. Then I checked this code manually with temporary browser extension

Changed files:
```
/usr/local/lib/node_modules/imba/lib/compiler/nodes.js
/usr/local/lib/node_modules/imba/src/compiler/nodes.imba
/usr/local/lib/node_modules/imba/imbac.js
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated/added documentation affected by my changes.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by scanf** [comment]
@somebee can you rebase this?

**Comment by somebee** [comment]
You can always declare them at the top of the file using `extern chrome, browser`. I think it could lead to surprising behaviour to include these as globals for everyone, so I don't think we should merge it.

Btw, we no longer resolve identifiers with implicit self in v2 so this won't be a problem going forward :)

**Comment by Friz-zy** [comment]
`extern chrome, browser` works, thank you :)
Maybe we should add more examples to the docs? Google find `extern` only in gitter channel xD
Imba need more good documentation, like imba-guide was :\

btw thank you for the imba :)
It's interesting entrance into web development after python background, problem only with docs\examples in compare with vanilla js and vuejs\react

**Comment by scanf** [comment]
The documentation will be revamped and other really cool things are in the works. Coming soon, but I am going to close this for now.

Thanks.

**Pull request closed without merging**
