### PR TITLE
Add slot/child feature

### PR DESCRIPTION
**Pull request by athif23**
With many days/weeks of learning the lexer and parser to see how it works, finally I have found a way to make #164 works. Well, I don't really test it in many thing but I think it will works fine. I have test it with my personal projects and it works fine (for now and I hope always).

### How to use it:
We just need to call `this.child` in some `tag`. Like so:
```imba
tag CustomTag
	def render
		<self>
			<div>
				this.child
```
But remember to add `!` after `<` when calling the tag, like this `<!CustomTag>`.

I don't know what the best syntax it should have, so I just use the `!` symbol.
Tell me if I should change it or not.

Thanks.

### CODE REVIEW

**Comment by somebee** [comment]
I'll take a look this weekend :) Thanks for the contribution!

**Comment by athif23** [comment]
Go ahead, please review it. Will wait for it.

**Comment by somebee** [comment]
Again, sorry for the delay. Pretty swamped here. Writing up some comments now.

**Comment by shreeve** [comment]
https://scrimba.com/c/cz6p83fd

**Comment by shreeve** [comment]
The link I just sent is from Ahmed Tarek @pushqrdx and it looks like he's got slots working.

**Comment by athif23** [comment]
I have know that, and I'm intended to close this once he PR his. 

Also @somebee please don't merge this, merge @pushqrdx has instead. It's more cool.

**Comment by somebee** [comment]
I opened issue #182 to track this.

**Comment by somebee** [comment]
Hey all. We have now implemented highly performant and versatile slots support in v2 (due for release relatively soon). You can see some examples here: https://github.com/imba/imba/blob/master/test/apps/slots/named-slots.imba.
We might want to add a special slot syntax like the one proposed in this PR, but we can move that discussion to an issue. Thank you for the PR - even if it isnt included it was the initial reason I implemented slots support in v2!

**Comment by athif23** [comment]
@somebee Good to know :) I would try to help as much as I can.

**Pull request closed without merging**
