### PR TITLE
ci: test Node.js 8, 10 and 11

### PR DESCRIPTION
**Pull request by DanielRuf**
`lts/*` tests only against Node.js 10. But 6, 8 and 10 are currently active LTS.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Seems Node.js 6 is not supported as the testsuite can not run there.

**Comment by somebee** [comment]
Interesting. Good catch. It's probably because we started compiling await to native async/await at some point. Do you think it's okay to stop supporting <8.0? It should be possible to differentiate compiling for these older targets, but feels sketchy since the non-native async/await works a little differently.

**Comment by DanielRuf** [comment]
> Interesting. Good catch. It's probably because we started compiling await to native async/await at some point. Do you think it's okay to stop supporting <8.0? It should be possible to differentiate compiling for these older targets, but feels sketchy since the non-native async/await works a little differently.

In this case we should make this clear in one of the upcoming major releases using `engines.node` in package.json.

**Comment by DanielRuf** [comment]
Will do so tomorrow.

**Comment by DanielRuf** [comment]
> Would you update this to remove 6 even if it is LTS? I have now updated to >=8.0.0 in latest release.

Done.

**Pull request merged**
