### PR TITLE
Made splats compatible with ES6 containers like Set. This branch will not work without ES6 or ES6 polyfills.

### PR DESCRIPTION
**Pull request by taw**
Addresses https://github.com/imba/imba/issues/166

### CODE REVIEW

**Comment by taw** [comment]
This one can be polyfilled, but honestly it's time to just drop non-ES6.

**Comment by taw** [comment]
I rebased it. Including compiled code in the repo results in some nasty merge conflicts.

**Comment by somebee** [comment]
Internet explorer still doesnt support Array.from. Is it okay for everyone to just use babel / a transpiler if they need it to work? I do agree that embracing ES6 is long overdue.

**Comment by taw** [comment]
You could include ES6 polyfills in imba if you want IE11 support. To be honest a lot of imba code already won't work on IE11 anyway, and a lot of frameworks dropped it years ago

**Comment by iamtirado** [comment]
🙌

**Pull request merged**
