### PR TITLE
#796 bug fix - no syntax errors in Vite bundler

### PR DESCRIPTION
**Pull request by madmaniak**

### CODE REVIEW

**Review by familyfriendlymikey — APPROVED** [review]
Tested with a couple codebases and working great. Thank you :)

**Comment by madmaniak** [comment]
Easy peasy. Can you let me know what is your flow for developing vite-imba-plugin?

**Comment by familyfriendlymikey** [comment]
Flow in terms of merging commits, or something else? I'm pretty confident we can just merge this one but since @haikyuu is in control of the plugin I wanted to let him take a look first.

**Comment by haikyuu** [comment]
You can merge @familyfriendlymikey 🙏

**Comment by haikyuu** [comment]
I will publish a new version afterwards

**Comment by madmaniak** [comment]
@familyfriendlymikey I mean how do you test your changes? Do you use npm run dev? Do you use npm run build at all at some point?

**Comment by familyfriendlymikey** [comment]
Yeah, for this one `dev` and `build`/`preview` suffice imo.

I do believe there is further testing here, but I haven't used it yet: https://github.com/imba/imba/tree/master/packages/e2e-tests

**Comment by haikyuu** [comment]
@madmaniak There are some tests. You can run them with `npm run test` in the vite-plugin-imba folder.

The tests are integration tests for the vite integration so they take around a minute to run (50s). But they are super useful and allow iterating on the vite integration easily.

Tests are a bunch of imba-vite apps we make sure run. They span from live reloading to svg, to server bundling. Adding another test is simply done by copying a folder (or making sure a couple of commands are defined in package.json)

I'm more than happy to assist you with more details, just ping me here or in discord 🙏 Glad to see more contributors to Imba

**Comment by haikyuu** [comment]
@madmaniak If you're interested, you can try adding a test case for displaying syntax errors in Vite. No need to create a new project. You can: 
- go to `e2e-tests/hmr` and add a new test case in env.spec.ts
- You should be able to create a syntax error in a running app by using `await updateApp((content) => content.replace("c:amber4", "c:green"));` and replace with something broken.

**Pull request merged**
