### PR TITLE
Allow an array or object to be passed as <tag .{classes}>

### PR DESCRIPTION
**Pull request by shreeve**

### CODE REVIEW

**Comment by shreeve** [comment]
This PR allows the classes of a tag to be passed an an `array` or an `object`. In this example, I have a method called `classes` that is totally dynamic. The other supplied methods in `imba` didn't seem to provide passing an `array` or `object`:

image

**Comment by shreeve** [comment]
image

**Comment by pushqrdx** [comment]
@shreeve  Could something like that be a more convenient fix for your issue?

```html
<Card.full-size class=' you can bind this to anything that returns space separated classes '> 
```

So as noted in the snippet you will just need to return your object with join(' ') and all the classes will be merged with the other concise classes you already have. A working example of this + my slot implementation can be found at this [scrimba](https://scrimba.com/c/c97rwqH8) and i'll be submitting a pr soon.

**Comment by somebee** [comment]
This is a very good idea, and something we need to support. But this implementation will not work when using multiple dynamic classes

```imba
<div .{dynamicOne} .{dynamicTwo}>
```

If any of them is an array you'll end up with weird behaviour. Also, when they are objects, the removal of a key will not remove the classname.

The concept *should* be pretty straight forward to support though.

**Comment by shreeve** [comment]
Ah, great points!

Ok, sounds like we're in the general direction, just need some refinements to make it solid.

**Pull request closed without merging**
