### PR TITLE
add module template to cli

### PR DESCRIPTION
**Pull request by familyfriendlymikey**
Module template: https://github.com/imba/imba-module-template

Tested and working with React, Vue, and Svelte.

It deserves its own template because:
- Incremental adoption is important, the fact that imba uses actual custom elements is a selling point.
- Several additions needed to be made to `vite.config.js`, `package.json`, and `main.imba`.

### CODE REVIEW

**Comment by familyfriendlymikey** [comment]
Is there a better name for this? Perhaps `module`? `component` might mislead people into thinking that you can only use the template to make a single component.

**Comment by haikyuu** [comment]
@familyfriendlymikey I don't think this should be added to cli. This is going to be used by advanced developers willing to use imba with their existing codebase.

It will be very confusing for newcomers.

IMO, Its place should be in the docs as a guide

**Comment by haikyuu** [comment]
One more thing: people willing to add imba to an existing Vite project only need to install the vite plugin and imba itself.
Having part of their code in a separate project is too cumbersome to be used in practice.

Providing a repo as a showcase of the pattern is the way to go.

**Comment by familyfriendlymikey** [comment]
Newcomers will just pick the base template, I don't think they will be confused by additional options. I also don't think having less options is better in this case. If anything `imba create` is a good opportunity to show all the different things you can make with Imba.

Advanced users will also see the module template in the cli when they create their first project and thereon know it exists. If more people start using Imba for real projects, many of them will want to know how to include Imba in their existing projects. If it's not in the cli, their only chance for exposure is one single location on imba.io.

And not everybody uses Vite in their existing projects. For those people, having an Imba module in their project is the only viable method. If that's genuinely too cumbersome in practice then there would be no reason to show the pattern in a repo or guide in the first place. If anything I think it's too cumbersome if it's *not* in the cli.

But I don't use other frameworks or make reusable components, so I don't have any personal benefit from the module template being included in the cli. This is just what I think would be best for adoption.

**Comment by trafnar** [comment]
Not sure if this is the right place to discuss this, but I found the new default template to be annoying, it shows off a bunch more features, and has a more modular design, but I kinda want an even more stripped down template than the old one (which was pretty stripped down).

Maybe there should be an option like "bare bones template" in addition to the more robust one.

**Comment by trafnar** [comment]
This module template is for creating a generic npm style module you can include into another project? I'd appreciate having that, I always have to re-create the boilerplate myself and forget how to do it each time... I also agree that it wouldn't confuse new users if it's just an option in the list (I assume beginners wouldn't choose it if they don't know what it is)

**Comment by familyfriendlymikey** [comment]
>  I kinda want an even more stripped down template than the old one

I totally agree, I put together a simplified vite template and converted all the external css and whatnot to Imba here: https://github.com/familyfriendlymikey/imba-vite-template. Maybe I can also just use a url for the svgs and delete the assets folder too.

I'd like to simplify the base template as well but since I already have multiple proposals pending I decided to wait on it.

**Comment by familyfriendlymikey** [comment]
> This module template is for creating a generic npm style module you can include into another project?

Yeah, this PR is somewhat paired with this incremental adoption guide: https://github.com/imba/imba.io/pull/255/files, but the template is also good for making npm packages and reusable components.

**Comment by haikyuu** [comment]
Ok then, let's ship it.

Also agree the templates should be simplified. And the default one shouldn't have an express server

**Review by haikyuu — APPROVED** [review]

**Pull request merged**
